'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ChevronRight, Music2, Tv, Shirt, Gamepad2, Utensils, Smartphone, Heart, X, Sun } from 'lucide-react';
import { categories, decades, getExhibits, type Category, type Exhibit } from '@/lib/data';
import { ListenButton } from './shell';
const icons=[Music2,Tv,Shirt,Gamepad2,Utensils,Smartphone,Heart];
export function GalleryDetail({decade}:{decade:typeof decades[number]}){
 const [category,setCategory]=useState<Category>('Music');const [selected,setSelected]=useState<Exhibit|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close()},[selected]);
 return <main id="main-content" className="detail page"><div className="ambient-art"/><div className="breadcrumbs"><Link href="/galleries">Galleries</Link><ChevronRight size={14}/><span>{decade.id}</span></div><section className="detail-hero"><div><h1 style={{color:decade.color}}>{decade.id}</h1><h2>{decade.title}</h2><p>{decade.description}</p></div><div className="memory-collage" aria-hidden="true"><div className="mini-polaroid"><div className="collage-image"/><span>the days we remember ♡</span></div><div className="paper mini-note">OPM<br/>Teen idols<br/>Text culture<br/>Pinoy movies<br/>Early internet <span>♡</span></div></div></section><div className="decade-switch" aria-label="Choose a decade">{decades.map(d=><Link key={d.id} href={`/galleries/${d.id}`} aria-current={d.id===decade.id?'page':undefined}>{d.id}</Link>)}</div><section className="exhibit-browser"><aside className="category-list" aria-label="Gallery categories">{categories.map((c,i)=>{const Icon=icons[i];return <button key={c} aria-pressed={c===category} onClick={()=>setCategory(c)}><Icon size={19}/>{c}</button>})}</aside><div className="exhibit-panel"><header><h2><Sun size={23}/>{category}</h2><span>0{categories.indexOf(category)+1} / 07</span></header><div className="exhibit-grid">{getExhibits(decade.id,category).map((e,i)=><button key={e.title} className="exhibit-card" onClick={()=>setSelected(e)}><div className={`exhibit-art art-${i}`}><span className="exhibit-number">0{i+1}</span><span className="art-symbol">{category==='Music'?['♫','✦','◉','♪'][i]:['✧','♡','✦','◈'][i]}</span></div><span className="exhibit-title">{e.title}<ArrowUpRight size={15}/></span></button>)}</div><div className="exhibit-bottom"><p>Every memory has a story. Open one to explore.</p><ListenButton/></div></div></section><dialog ref={dialog} className="story-dialog" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}}>{selected&&<><button className="icon-button close-dialog" aria-label="Close story" onClick={()=>setSelected(null)}><X/></button><div className="story-art"/><div className="story-copy"><p className="eyebrow">{selected.tag}</p><h2>{selected.title}</h2><p>{selected.description}</p><p className="memory-prompt">What does this bring back for you?</p><small>Illustrative exhibit · part of our shared cultural scrapbook</small></div></>}</dialog></main>
}
